### PR TITLE
support for <i>obliqueness</i>

### PR DESCRIPTION
**Pull request by dbankier**

### CODE REVIEW

**Comment by FokkeZB** [comment]
Thanks, could you add `<em>` as well?

**Comment by yuchi** [comment]
There should be also `<mark>` in inline elements. The problem is that you cannot know which color the dev wants (the std browser impl uses just a yellow bg).

**Comment by FokkeZB** [comment]
Maybe just check what color Android uses (if it supports it) and then use the same for parity.

**Comment by FokkeZB** [comment]
@yuchi Could you create a separate ticket?

**Comment by yuchi** [comment]
The `mark` issue is #9

**Comment by dbankier** [comment]
Done.

**Pull request merged**
