### PR TITLE
Added showNewLines property

### PR DESCRIPTION
**Pull request by williamrijksen**
On iOS new lines didn't show. This PR adds the possibility to prevent removing the new lines.

### CODE REVIEW

**Comment by FokkeZB** [comment]
That is expected behaviour as in HTML newlines are not shown.

**Comment by williamrijksen** [comment]
@FokkeZB How can i make sure that ```<br />``` tags are shown on iOS?

**Comment by FokkeZB** [comment]
Those should work. If they don't then that's a bug. Please create a new issue and include a PR with test case (in the test branch).

**Comment by williamrijksen** [comment]
@FokkeZB The example in the example directory doesn't create new lines on iOS in my case. I'll create an issue for this.

**Pull request closed without merging**
