### PR TITLE
added Smart New Lines behaviour for handling block elements

### PR DESCRIPTION
**Pull request by balanza**
As discussed in https://github.com/FokkeZB/ti-html2as/issues/18, these changes implements new line behaviour for block elements. This feature needs a flag to be activate, otherwise it works as before.

### CODE REVIEW

**Comment by FokkeZB** [comment]
@balanza thanks. However, this does not seem to be compatible with https://github.com/FokkeZB/ti-html2as/commit/7a9325334374ad95ddc02d10f73eacc5cef0460b where I now strip out all newlines. Could you make it compatible with that change? Probably should use `<br>` tags instead.

**Comment by FokkeZB** [comment]
Also, update the example so it demonstrates the test.

**Comment by FokkeZB** [comment]
I'd also prefer to have a generic `opts` argument instead which you'd pass on to the walker

```
/**
 * Module's core function 
 * 
 * @param  {string}   html               source html to be processed
 * @param  {Object}   opts               options
 * @param  {boolean}  opts.blocks        flag to add newlines around html block elements
 * @param  {Function} callback           callback function, in the form (err, result)
 */
module.exports = function (html, opts, callback) {

  if (arguments.length === 2) {
    callback = opts;
    opts = {};
  } else {
    opts = opts || {};
  }

  var parser = new htmlparser.Parser(new htmlparser.DomHandler(function (error, dom) {

    if (error) {
      callback(error);

    } else {

      var parameters = walker({
        type: 'tag',
        children: dom
      }, {
        text: '',
        attributes: []
      }, opts);

      var attr = ns.createAttributedString(parameters);

      callback(null, attr);
    }
  }));

  // remove newlines
  html = html.replace(/[\r\n]+/gm, ' ').replace(/\s+/g, ' ');

  parser.parseComplete(html);

};
```

**Comment by balanza** [comment]
Hi @FokkeZB, 

I see this PR is still open. I understand that we should use  http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI-property-ATTRIBUTE_LINE_BREAK for handling line breaks, thus I think we can close the PR.

**Comment by FokkeZB** [comment]
Well, that's not exactly the same. That doesn't handle injecting blank limes before/after tags like p, h* etc.

**Comment by yuchi** [comment]
May also bring to life the complete absence of ParagraphStyle in Titanium?

**Comment by FokkeZB** [comment]
@yuchi you mean https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/ApplicationKit/Classes/NSMutableParagraphStyle_Class/index.html ?

**Comment by yuchi** [comment]
Yeah.

**Comment by FokkeZB** [comment]
Could you create a JIRA ticket for that @yuchi ?

**Comment by yuchi** [comment]
Now waiting the triage to do its magic: https://jira.appcelerator.org/browse/TC-5717

**Comment by FokkeZB** [comment]
Closing for inactivity

**Pull request closed without merging**
